### ISSUE TITLE
右下角图标拖动范围限制及功能改进建议

### ISSUE THREAD

**Issue by Leafuke** [Alan-CRL/Intelligent-Drawing-Teaching#1]
版本号：20240128a
操作系统：Windows11
机型：Surface Laptop Go2
问题及建议：1. 程序图标只能在右下角一定矩形范围内拖动，无法放置到左下角。这貌似是特地设计避免工具栏遮挡。但是有没有办法使它自适应或者单独发布一个向右展开的版本呢？考虑到老师日常使用习惯。
2. 图标大小能够调整的话就更好了。

**Comment by Alan-CRL** [comment]
是的，这些功能已经基本完成并正在测试，向右展开和图标大小调整都隶属于智绘教UI3.0的范畴，我们将对UI进行大改，拥有2种预设（PC小图标和触摸设备大图标模式，并拥有高度的自定义化）。同时改善程序逻辑，提高效率。感谢对智绘教的支持！
