### ISSUE TITLE
一些建议和bug反馈

### ISSUE THREAD

**Issue by lh11117** [Alan-CRL/Intelligent-Drawing-Teaching#12]
尊敬的智教绘开发团队：
我近期使用智教绘时，遇到了一些问题，在此提出：
1. 建议：
加入对 `Libre Office`、`Only Office` 的支持
2. bug：
智教绘可以无限启动，导致桌面上一堆悬浮窗
![Snipaste_2024-03-01_20-58-57](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/99455215/02e03e14-8229-48de-9e0f-586f3adde7b2)

**Comment by ALTaleX531** [comment]
什么类Office软件都要支持，未免有点抽象了

**Comment by Alan-CRL** [comment]
@lh11117 感谢您的支持。

对于第一个建议，首先了解到 `Libre Office` 和 `Only Office` 是使用与 MsPPT 不一样的组件进行交互的，接下来会对不支持的 PPT 软件做初步的支持，如翻页按钮等。目前的难点在于智绘教需要获取 PPT 软件的信息（如当前页数和总页数等），兼容更多的 Office 就需要编写不同的交互代码，您的建议我会考虑，稍后我会对这些 Office 的对接难度做个评估。不过需要注意的是，这项工作不是当前的重心，此功能上线需要较长的时间或不会上线，我还是建议您使用 MsOffice 或 WPS 的主流演示软件。

对于第二点，这个问题很早就注意到了，不过有一些特殊场景存在 2 个智绘教同时打开的，比如更新时或者崩溃时，所以这项问题的解决需要待崩溃助手模块重新设计后再考虑。我觉得这并不重要，只要你不刻意打开两次就行。

最后再次感谢您对智绘教的支持与肯定！此 Issues 暂时处于 Open 状态，待建议有了决定后再关闭。

**Comment by Alan-CRL** [comment]
@lh11117 对于问题2，已经在 [此处](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/commit/f362e6ebc3bc9145130b4b42ee097e5078819a0c) 修复，稍后可以在正式版本中体验到。
