### ISSUE TITLE
实际教学使用过程中遇到的问题汇总

### ISSUE THREAD

**Issue by Leafuke** [Alan-CRL/Intelligent-Drawing-Teaching#14]
在两个班级推广使用智绘教，已使用两个星期，观察老师使用情况。

首先，智绘教在操作“人性化”方面做得很不错👍。优点不一一例举，这里主要讨论遇到的问题~

**希沃版本**：未知
**操作系统**：Windows10
**安装的软件**：MS Office 2021 LTSC标准版、WPS 2024
**使用的版本**：[Ver2402.3](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/releases/tag/20240228a)、[Ver2402.2](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/releases/tag/20240220c)

**问题1**：与希沃的PPT冲突
**描述**：部分老师使用希沃的云课件，教学过程中如果智绘教程序存在，有概率触发希沃PPT页面按钮失效，无法点击。关闭智绘教后恢复正常（有时候也不会恢复）
**推测原因**：未知
**可能的临时解决方法**：检测到使用希沃演示时自动“让位”

**问题2**：MS Office PPT联动冲突
**描述**：在展示PPT时大部分情况下会和希沃的联动同时出现，有小概率会成功压制希沃联动（
WPS 2024 暂不支持，未测试
**推测原因**：MS Office和WPS同时存在造成的bug？
**可能的临时解决方法**：增加PPT联动开关选项，在 3.0 PPT联动上优胜希沃后进行完全替代。或许可以直接换掉WPS 2024

**问题3**：MS Office PPT联动按钮失效
**描述**：版本 [Ver2402.3](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/releases/tag/20240228a) 的PPT联动中，PPT联动的所有按钮会时不时失灵。在 [Ver2402.2](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/releases/tag/20240220c) 中不存在这个问题。
**推测原因**：⌈新的按键消息处理机制⌋可能存在一点点问题😂（还没有认真看源代码，不能确定）
**可能的临时解决方法**：未知。

**问题4**：平滑轨迹处理
**描述**：这是一个次要问题，即仔细对比之下，希沃的笔画平滑处理更加自然，这一点可以完善（但是在响应速度上优于希沃）

**功能建议**：类似 OneNote 的自动图形功能，可以作为一个默认关闭的选项。毕竟智绘教深受数学老师的喜爱，可以以此切入~~取代seewo~~

以上是遇到的主要问题。其他的小问题因为没有确凿证据所以暂时放着。期待未来的完善！

**Comment by Alan-CRL** [comment]
@Leafuke 我是智绘教开发者 AlanCRL，非常感谢您的耐心。

对于**问题一**：了解到智绘教 PPT 控件与希沃 PPT 冲突是因为希沃 PPT 使用的同为 MS 内核，所以会被智绘教捕获到。您提到的让位，是个很好的思路。我将在接下来的一周内解决这个问题。

对于**问题二**：您提到与希沃 PPT 小工具冲突，是这样的。如果您真切想使用智绘教的 PPT 组件，那可以卸载希沃 PPT 小工具，这样就不会冲突了。 对于“进行完全替代”我会考虑对希沃PPT小工具进行封杀的操作，但前提是完成 UI 3.0 的制作。补充：智绘教是兼容 WPS2024 的，您可以重新安装再试，确认勾选“兼容第三方软件”选项。

对于 **问题三**：该问题已在 `智绘教20240309b` 中解决，请前往网盘下载最新版本或是等待自动更新。

对于 **问题四**：希沃的绘制模块并不是希沃的，来自 MS 的 WPF。而智绘教的绘制模块均为手搓出来的，效果肯定比不上微软。但是实时平滑和模拟笔锋等事项已经在路上了……

最后再次感谢对智绘教的支持，如果还有什么问题也欢迎提出。
