### ISSUE TITLE
CPU占用问题

### ISSUE THREAD

**Issue by Leafuke** [Alan-CRL/Intelligent-Drawing-Teaching#2]
版本号：20240128a
操作系统：Windows11
机型：Surface Laptop Go2
CPU：i5-1135G7 四核处理器

在启动程序，没有任何操作的情况下，CPU占用持续为5%~8%
此占用率可以说相对较高了。希望能够进行一些优化。

**Comment by Alan-CRL** [comment]
目前来说我们正在考虑制作动态刷新率的功能，主界面固定为24帧每秒刷新，可能是导致这个问题的关键。感谢对智绘教的支持！
