### ISSUE TITLE
windows11 打开软件自动退出

### ISSUE THREAD

**Issue by xiaoyuit** [Alan-CRL/Intelligent-Drawing-Teaching#21]
版本号 20240504a

![image](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/5516423/8678cf4b-16f2-4ef7-9c3f-7fd11aeeca54)
![image](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/5516423/3e7a4d23-e62a-459d-b623-11bed10e8244)

**Comment by Alan-CRL** [comment]
非常抱歉我漏过了此 Issus，我将在明天进行回复

**Comment by Alan-CRL** [comment]
@xiaoyuit 请先升级到最新Beta版本：[智绘教20240519b](https://www.123pan.com/s/duk9-4x3Ad.html) 然后我需要更加详细的信息，包括：系统版本、系统分辨率、开启程序后程序根目录下 log 文件夹中日志等。感谢您的理解与耐心支持~

**Comment by xiaoyuit** [comment]
Beta版本执行，360安全卫士报：HEUR/QVM41.2.9E7E.Malware.Gen，添加信任后可以打开，但是系统部分软件卡死
系统版本：
Windows 11 专业版 23H2
分辨率：
1920*1080 双屏扩展
日志：
`[info][09:45:49.123][主线程][IdtMain] 日志开始记录 {2d8f50f1-7232-5f82-0000-00003e6cc700}
[info][09:45:49.123][主线程][IdtMain] 初始化DPI
[info][09:45:49.123][主线程][IdtMain] 加载Shcore.dll
[info][09:45:49.124][主线程][IdtMain] 加载Shcore.dll成功
[info][09:45:49.124][主线程][IdtMain] 查询接口SetProcessDpiAwareness
[info][09:45:49.124][主线程][IdtMain] 执行SetProcessDpiAwareness
[info][09:45:49.124][主线程][IdtMain] 查询接口SetProcessDpiAwareness成功
[info][09:45:49.124][主线程][IdtMain] 执行SetProcessDpiAwareness成功
[info][09:45:49.131][主线程][IdtMain] 初始化DPI完成
[info][09:45:49.131][主线程][IdtMain] 初始化字体
[info][09:45:49.131][主线程][IdtMain] 加载字体
[info][09:45:49.142][主线程][IdtMain] 加载字体完成
[info][09:45:49.143][主线程][IdtMain] 设置字体
[info][09:45:49.143][主线程][IdtMain] 设置字体完成
[info][09:45:49.143][主线程][IdtMain] 监视器信息查询
[info][09:45:49.143][主线程][IdtMain] 初始化监视器信息
[info][09:45:49.143][主线程][IdtMain] 初始化字体完成
[info][09:45:49.143][主线程][IdtMain] 初始化配置信息
[info][09:45:49.143][主线程][IdtMain] MagnifierThread函数线程启动
[info][09:45:49.143][主线程][IdtMain] 监视器信息查询完成
[info][09:45:49.143][主线程][IdtMain] 读取配置信息
[warning][09:45:49.143][主线程][IdtMain] 拥有多个监视器
[info][09:45:49.143][主线程][IdtMain] 初始化监视器信息完成
[info][09:45:49.194][放大API线程][MagnifierThread] 初始化MagInitialize
[info][09:45:49.194][放大API线程][MagnifierThread] 初始化MagInitialize完成
[info][09:45:49.194][放大API线程][SetupMagnifier] 注册放大API主机窗口
[info][09:45:49.195][主线程][IdtMain] 读取配置信息完成
[info][09:45:49.194][放大API线程][MagnifierThread] 启动放大API
[info][09:45:49.195][主线程][IdtMain] 更新配置信息
[info][09:45:49.194][放大API线程][SetupMagnifier] 创建放大API主机窗口
[info][09:45:49.194][放大API线程][SetupMagnifier] 注册放大API主机窗口完成
[info][09:45:49.195][主线程][IdtMain] 更新配置信息完成
[info][09:45:49.196][主线程][IdtMain] 初始化COM
[info][09:45:49.196][主线程][IdtMain] 初始化CoInitialize
[info][09:45:49.205][主线程][IdtMain] 初始化CoInitialize完成
[info][09:45:49.205][主线程][IdtMain] 初始化PptCOM.dll
[info][09:45:49.208][放大API线程][SetupMagnifier] 创建放大API主机窗口完成
[info][09:45:49.208][放大API线程][SetupMagnifier] 设置放大API主机窗口透明度
[info][09:45:49.209][放大API线程][SetupMagnifier] 设置放大API主机窗口透明度完成
[info][09:45:49.209][放大API线程][SetupMagnifier] 创建放大API窗口
[info][09:45:49.231][主线程][IdtMain] 初始化PptCOM.dll完成
[info][09:45:49.231][主线程][IdtMain] 初始化上下文API
[info][09:45:49.233][主线程][IdtMain] 初始化上下文API完成
[info][09:45:49.233][主线程][IdtMain] 载入PptCOM.dll
[info][09:45:49.236][主线程][IdtMain] 载入PptCOM.dll完成
[info][09:45:49.236][主线程][IdtMain] 初始化COM完成
[info][09:45:49.236][主线程][IdtMain] 创建定格背景窗口
[info][09:45:49.397][主线程][IdtMain] 创建定格背景窗口完成
[info][09:45:49.397][主线程][IdtMain] 创建画板窗口
[info][09:45:49.453][主线程][IdtMain] 创建画板窗口完成
[info][09:45:49.453][主线程][IdtMain] 创建PPT批注控件窗口
[info][09:45:49.515][主线程][IdtMain] 创建PPT批注控件窗口完成
[info][09:45:49.515][主线程][IdtMain] 创建悬浮窗窗口
[info][09:45:49.578][主线程][IdtMain] 创建悬浮窗窗口完成
[info][09:45:49.674][放大API线程][SetupMagnifier] 创建放大API窗口完成
[info][09:45:49.674][放大API线程][SetupMagnifier] 设置放大API窗口样式
[info][09:45:49.720][放大API线程][SetupMagnifier] 设置放大API窗口样式完成
[info][09:45:49.720][放大API线程][SetupMagnifier] 设置放大API工厂完成
[info][09:45:49.720][放大API线程][SetupMagnifier] 设置放大API转换矩阵
[info][09:45:49.720][放大API线程][SetupMagnifier] 设置放大API工厂
[info][09:45:49.745][放大API线程][SetupMagnifier] 设置放大API转换矩阵完成
[info][09:45:49.745][放大API线程][SetupMagnifier] 更新放大API窗口
[info][09:45:49.745][放大API线程][MagnifierThread] 启动放大API完成
[info][09:45:49.759][放大API线程][SetupMagnifier] 更新放大API窗口完成
[info][09:45:49.759][放大API线程][SetupMagnifier] 启动放大API服务进程
[info][09:45:49.760][放大API线程][SetupMagnifier] 启动放大API服务进程成功
[info][09:45:49.760][放大API线程][MagnifierThread] 等待穿透窗口创建
[info][09:45:49.781][主线程][IdtMain] TopWindow函数线程启动
[info][09:45:49.781][主线程][IdtMain] 初始化RTS触控库
[info][09:45:49.782][窗口置顶线程][TopWindow] 等待窗口初次绘制
[info][09:45:49.895][主线程][IdtMain] RTSSpeed函数线程启动
[info][09:45:49.895][主线程][IdtMain] 初始化RTS触控库完成
[info][09:45:49.895][主线程][IdtMain] drawpad_main函数线程启动
[info][09:45:49.895][主线程][IdtMain] floating_main函数线程启动
[info][09:45:49.895][主线程][IdtMain] SettingMain函数线程启动
[info][09:45:49.895][主线程][IdtMain] FreezeFrameWindow函数线程启动
[info][09:45:50.283][窗口置顶线程][TopWindow] 等待窗口初次绘制完成
[info][09:45:50.283][窗口置顶线程][TopWindow] 显示窗口
[info][09:45:50.330][窗口置顶线程][TopWindow] 显示窗口完成
[info][09:45:50.761][放大API线程][MagnifierThread] 设置穿透窗口列表
[info][09:45:50.761][放大API线程][MagnifierThread] 设置穿透窗口列表完成
[info][09:45:50.761][放大API线程][MagnifierThread] 等待穿透窗口创建完成
[info][09:47:01.825][窗口置顶线程][TopWindow] 隐藏窗口
[info][09:47:01.845][窗口置顶线程][TopWindow] 隐藏窗口完成
[info][09:47:01.980][主线程][IdtMain] 等待各函数线程结束
[info][09:47:07.487][主线程][IdtMain] 反初始化 COM 环境
[info][09:47:07.487][主线程][IdtMain] 初始化CoUninitialize
[info][09:47:07.489][主线程][IdtMain] 初始化CoUninitialize完成
[info][09:47:07.489][主线程][IdtMain] 释放上下文API
[info][09:47:07.489][主线程][IdtMain] 释放上下文API完成
[info][09:47:07.489][主线程][IdtMain] 反初始化 COM 环境完成
[info][09:47:07.489][主线程][IdtMain] 等待崩溃重启助手结束
[info][09:48:10.557][主线程][IdtMain] 崩溃重启助手结束
[info][09:48:10.557][主线程][IdtMain] 已结束智绘教所有线程并关闭程序
`

**Comment by Alan-CRL** [comment]
根据日志文件，我看到智绘教是正常运行的，说明这个问题应该修复了。

- 首先 Beta 版本的文件不会向 360 进行报备并解除误报，所以这是正常现象  
-  其次您提到的 `但是系统部分软件卡死` 我不能确定是智绘教的问题，需要更详细的内容如视频说明等  
- 最后双屏下智绘教目前只支持在主显示器上绘图  

感谢您对智绘教的支持，对于第二点如果没有更多信息，可以关闭此 Issus，谢谢~

**Comment by xiaoyuit** [comment]
> 根据日志文件，我看到智绘教是正常运行的，说明这个问题应该修复了。
> 
> * 首先 Beta 版本的文件不会向 360 进行报备并解除误报，所以这是正常现象
> * 其次您提到的 `但是系统部分软件卡死` 我不能确定是智绘教的问题，需要更详细的内容如视频说明等
> * 最后双屏下智绘教目前只支持在主显示器上绘图
> 
> 感谢您对智绘教的支持，对于第二点如果没有更多信息，可以关闭此 Issus，谢谢~

重启电脑后，在测试已经可以正常使用，感谢！
