### ISSUE TITLE
智绘教 PPT联动模块 意见和漏洞收集

### ISSUE THREAD

**Issue by Alan-CRL** [Alan-CRL/Intelligent-Drawing-Teaching#7]
目前智绘教 PPT联动 仅支持 MsPPT 

曾有用户报告过在 32位 MsPPT 环境下 PPT联动 不会正常工作，但是并没有详细信息。  
同时已知如果同时安装了WPS 2024（并启用了兼容第三方系统和软件），PPT联动模块会受到干扰，但原因不明。  

目前可以确定的是，我们接下来会做一个底栏，可以快速切换画笔橡皮等等。然后是适配WPS。但是目前看并没有什么这样的需求，如果没有这方面的用户需求，这些功能的实现将会延后。

**Comment by xrgzs** [comment]
现在希沃一体机的PC模块从MT51开始就已经预装WPS个人版，许多老师已经用习惯WPS，且部分课件的动画只支持使用WPS才能正常播放。另外WPS对触摸屏的优化不是特别好，对PPT辅助工具更加依赖。部分单位可能会有正版化要求，只能使用采购的WPS专业版。所以还是有适配WPS个人版+专业版的用户需求，建议尽量将适配WPS的工作提上日程。

**Comment by I-AM-A-NOOB** [comment]
请问是否有所有控件置于双侧边缘中部的选项？（_手头并无环境以测试_）由于老师已习惯鸿合PPT助手按钮置于侧边的布局，并且**大部分近视**，几次让其迁移到希沃PPT助手都以失败告终。若无，望提供此选项，以切实改进在鸿合设备上的体验

**Comment by Alan-CRL** [comment]
目前控件置于程序左右下角，而不是屏幕的左右两侧，不过这项功能我们以后会考虑的，感谢对智绘教的支持！

**Comment by I-AM-A-NOOB** [comment]
> 请问是否有所有控件置于双侧边缘中部的选项？（_手头并无环境以测试_）由于老师已习惯鸿合PPT助手按钮置于侧边的布局，并且**大部分近视**，无视屏幕底部按钮；几次让其迁移到希沃PPT助手都以失败告终。若无，望提供此选项，以切实改进在鸿合设备上的体验

![image](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/111118649/b3478d86-9435-4e3c-961f-b1ed4d32ab5a)
鸿合UI大致如图所示，对于用户的脊柱似乎更友好。
（用PowerPoint随手画的）

**Comment by Alan-CRL** [comment]
> 请问是否有所有控件置于双侧边缘中部的选项？（_手头并无环境以测试_）由于老师已习惯鸿合PPT助手按钮置于侧边的布局，并且**大部分近视**，无视屏幕底部按钮；几次让其迁移到希沃PPT助手都以失败告终。若无，望提供此选项，以切实改进在鸿合设备上的体验

@xrgzs 智绘教已经在尝试适配新版 WPS 了，目前正式发布版本已经兼容 WPS 2016 和 WPS 2019，但是对于 WPS 2024 依旧存在问题，由于官方更改了 WPP 核心，但是没有更新文档，所以此项开发进程需要暂停一段时间。同时我也咨询了官方，但是没有得到非常有用的解答。  

感谢对智绘教的建议与支持，我依旧会关注这项功能的实现的。

**Comment by Alan-CRL** [comment]
> 现在希沃一体机的PC模块从MT51开始就已经预装WPS个人版，许多老师已经用习惯WPS，且部分课件的动画只支持使用WPS才能正常播放。另外WPS对触摸屏的优化不是特别好，对PPT辅助工具更加依赖。部分单位可能会有正版化要求，只能使用采购的WPS专业版。所以还是有适配WPS个人版+专业版的用户需求，建议尽量将适配WPS的工作提上日程。

@xrgzs 智绘教已经在尝试适配新版 WPS 了，目前正式发布版本已经兼容 WPS 2016 和 WPS 2019，但是对于 WPS 2024 依旧存在问题，由于官方更改了 WPP 核心，但是没有更新文档，所以此项开发进程需要暂停一段时间。同时我也咨询了官方，但是没有得到非常有用的解答。

感谢对智绘教的建议与支持，我依旧会关注这项功能的实现的。

**Comment by Alan-CRL** [comment]
@xrgzs 再次感谢您对智绘教的支持，WPS联动已经完成开发，您可以稍后在正式版中体验到此功能，或是可以加入智绘教官方Q群体验这项功能！

**Comment by Leafuke** [comment]
版本：Ver2403.1
使用智绘教打开PPT，进行幻灯片放映会正常进入加载。但结束放映时有概率会再次出现加载界面。
这种情况在MS Office和WPS中均会出现。

次要问题：PPT联动的加载速度以及响应速度可以有所提升（注：响应速度指打开PPT到开始加载的时间，这个延迟的时间从1秒到几十秒不等）

**Comment by Alan-CRL** [comment]
@Leafuke 对于问题1：该问题已经在20240317a中修复，稍后您可以下载正式版并体验。对于2：这个问题我打算后面再优化逻辑，不过理论上最多5秒吧~

**Comment by Alan-CRL** [comment]
智绘教 PPT联动模块 已经修复所有已知问题，并将加载时间缩短到了极致，此 issues 将关闭！
