### ISSUE TITLE
请求增加对压感笔的支持

### ISSUE THREAD

**Issue by xrgzs** [Alan-CRL/Intelligent-Drawing-Teaching#9]
尊敬的开发团队，

我在使用智绘教软件时发现，该软件**似乎不支持压感笔**。我尝试使用压感笔进行绘图，但无法实现预期的效果，绘制出来的**笔迹生硬卡顿，没有笔锋**。另外，我使用**压感笔上的橡皮按钮**，无法将智绘教软件切换为橡皮擦除状态。

我认为压感笔支持对于画笔程序来说是一个重要的功能，它可以提供更自然和精细的绘图体验。我希望你们能考虑在未来的版本中添加对压感笔的支持。

谢谢！

附-详细说明：

使用版本：

![](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/26499123/60e5bf19-37cb-4ada-a19d-1b78472acf9d)
![](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/26499123/f470793f-29ce-40ea-9504-1e46d347ca53)
![](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/26499123/2de2d252-883e-467b-a034-c4c0eb4ef557)

笔迹生硬卡顿，没有笔锋：

![](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/26499123/0683a92e-f85b-4535-b75f-3dbe84a6c2ab)

并非设备问题，使用 MS PPT、截图工具、[WXRIW/Ink-Canvas](https://github.com/WXRIW/Ink-Canvas) 等程序均能正常压力感应：

![](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/26499123/793aa7e8-1c1d-4b8c-8051-225db8672ccf)

另外程序的CPU占用也是比较高，可能会导致体验卡顿：

![](https://github.com/Alan-CRL/Intelligent-Drawing-Teaching/assets/26499123/68f4055d-71b1-4801-8968-6b5378be1014)

参考：https://learn.microsoft.com/zh-cn/windows/apps/design/input/pen-haptics

**Comment by Alan-CRL** [comment]
感谢您对智绘教的支持，我们已经收到了您的反馈。首先针对占用率高这件事情，目前是我们正在解决的。对于笔的压根来说，我们会先做手抖修正->模拟压感->笔触压感。我们目前正在想办法编写绘制渐变粗细曲线的代码，然后会接入Windows Ink库，然后兼容笔触和数位板，但是这项功能进度会稍微变慢，智绘教目前主要的重心是教学触摸屏，和PC批注。
